FROM node:latest

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install dependencies
COPY package.json .
RUN npm install --silent

# Bundle app source
COPY . .

# Exports
ARG PORT
EXPOSE $PORT
CMD [ "npm", "run", "local:dev" ]