version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.dev
            args:
                - PORT=5000
        environment:
            PORT: 5000
            REDIS_URL: redis://redis:6379
            NODE_ENV: development
            MONGODB_URI: mongodb://mongo:27017/MyApp
            MONGODB_URI_TEST: mongodb://mongo:27017/MyApp
            DOCUMENTATION_USER: admin
            DOCUMENTATION_PASSWORD: admin
        ports:
            - "5000:5000"
        volumes:
            - ./:/usr/src/app
            - /usr/src/app/node_modules # Remove this if you have pure JS dependencies
        depends_on:
            - redis
            - mongo
    mongo:
        image: mongo:latest
        volumes:
            - ~/MongoDB/data:/data/db
        ports:
            - "27017:27017"
        logging:
            driver: none
    redis:
        image: redis:latest
        command: ["redis-server", "--bind", "redis", "--port", "6379"]
        volumes:
            - ~/RedisDB/data:/data/db
        ports:
            - "6379:6379"
        logging:
            driver: none
